var ZagatVegiRestaurantData = {
Narcissa: {
	Name: 'Narcissa',
		Place: 'East Village',
		Type: 'American',
		BestDish:'Carrots Wellington',
		Price: "$20",
		zagatCity: 'New York City',
		Category: 'Best Restaurants For Vegetarians in NYC',
		date: 'September 9, 2018',
		Author: 'Zagat Staff',
		FoodReview: '4.5',
		DecorReview: '4.1',
		ServiceReview: '4.1',

	},
	Barbolonat: {
		Name: 'Barbolonat',
			Place: 'West Village',
			Type: 'Middle Eastern',
			BestDish:'Everyday Cauliflower',
			Price: '$9',
			zagatCity: 'NYC',
			Category: 'Best Restaurants For Vegetarians in NYC',
			date: 'September 9, 2018',
			Author: 'Zagat Staff',
			FoodReview: '4.5',
			DecorReview: '4.0',
			ServiceReview: '4.1',

		},
	Rosette: {
		Name: 'Rosette',
				Place: 'East Village',
				Type: 'American',
				BestDish:'Parsnip "Steak"',
				Price: '$16',
				zagatCity: 'New York City',
				Category: 'Best Restaurants For Vegetarians in NYC',
				date: 'September 9, 2018',
				Author: 'Zagat Staff',
				FoodReview: '4.5',
				DecorReview: '4.1',
				ServiceReview: '4.1',

			},
			Skal: {
				Name: 'Skal',
					Place: 'Canal Street',
					Type: 'American',
					BestDish:'Charred Broccoli',
					Price: '$11',
					zagatCity: 'New York City',
					Category: 'Best Restaurants For Vegetarians in NYC',
					date: 'September 9, 2018',
					Author: 'Zagat Staff',
					FoodReview: '4.5',
					DecorReview: '4.1',
					ServiceReview: '4.1',

				},
				TheCleveland: {
					Name: 'TheCleveland',
						Place: 'Cleveland Pl.',
						Type: 'Mediterranean',
						BestDish:'Grilled Whole Eggplant',
						Price: '$22',
						zagatCity: 'New York City',
						Category: 'Best Restaurants For Vegetarians in NYC',
						date: 'September 9, 2018',
						Author: 'Zagat Staff',
						FoodReview: '4.5',
						DecorReview: '4.1',
						ServiceReview: '4.1',

					},
					Annisa: {
						Name: 'Annisa',
							Place: 'Barrow Street',
							Type: 'American',
							BestDish:'GrilledHearts of Palms',
							Price: '$51',
							zagatCity: 'New York City',
							Category: 'Best Restaurants For Vegetarians in NYC',
							date: 'September 9, 2018',
							Author: 'Zagat Staff',
							FoodReview: '4.5',
							DecorReview: '4.1',
							ServiceReview: '4.1',

						},
						Piora: {
							Name: 'Piora',
								Place: 'Hudson Street',
								Type: 'American',
								BestDish:'Market Vegetables',
								Price: '$18',
								zagatCity: 'New York City',
								Category: 'Best Restaurants For Vegetarians in NYC',
								date: 'September 9, 2018',
								Author: 'Zagat Staff',
								FoodReview: '4.5',
								DecorReview: '4.1',
								ServiceReview: '4.1',

							},
							SnackTaverna: {
								Name: 'SnackTaverna',
									Place: 'Bedford Street',
									Type: 'American',
									BestDish:'Stuffed Sweet Red Pepper',
									Price: '$22',
									zagatCity: 'New York City',
									Category: 'Best Restaurants For Vegetarians in NYC',
									date: 'September 9, 2018',
									Author: 'Zagat Staff',
									FoodReview: '4.5',
									DecorReview: '4.1',
									ServiceReview: '4.1',

								},
								Sripraphai: {
									Name: 'Sripraphai',
										Place: 'Queens',
										Type: 'American',
										BestDish:'Crispy Chinese Watercress Salad',
										Price: '$11',
										zagatCity: 'New York City',
										Category: 'Best Restaurants For Vegetarians in NYC',
										date: 'September 9, 2018',
										Author: 'Zagat Staff',
										FoodReview: '4.5',
										DecorReview: '4.1',
										ServiceReview: '4.1',

									},
									Tessa: {
										Name: 'Tessa',
											Place: 'Amsterdam Avenue',
											Type: 'American',
											BestDish:'Green-Asparagus Risotto',
											Price: '$36',
											zagatCity: 'New York City',
											Category: 'Best Restaurants For Vegetarians in NYC',
											date: 'September 9, 2018',
											Author: 'Zagat Staff',
											FoodReview: '4.5',
											DecorReview: '4.1',
											ServiceReview: '4.1',

										},
										CandleCafe: {
											Name: 'CandleCafe',
												Place: 'East 70th Street',
												Type: 'Organic Vegan Cuisine',
												BestDish:'Gwyneth Paltrow Wannabes',
												Price: '$18',
												zagatCity: 'New York City',
												Category: 'Best Restaurants For Vegetarians in NYC',
												date: 'September 9, 2018',
												Author: 'Zagat Staff',
												FoodReview: '4.3',
												DecorReview: '3.7',
												ServiceReview: '4.0',

											},
											Hangawi: {
												Name: 'Hangawi',
													Place: 'Murray Hill',
													Type: 'Korean',
													BestDish:'Carrots Wellington',
													Price: '$15',
													zagatCity: 'New York City',
													Category: 'Best Restaurants For Vegetarians in NYC',
													date: 'September 9, 2018',
													Author: 'Zagat Staff',
													FoodReview: '4.5',
													DecorReview: '4.4',
													ServiceReview: '4.4',

												}


};
